# config file version
apiVersion: 2

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://$ENV_PROMETHEUS_IP:9090
    isDefault: true
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://$ENV_LOKI_IP:3100
    isDefault: false
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
