{
 "title": "Chia on Windows",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "disks",
    "query": {
     "query": "label_values(windows_logical_disk_free_bytes, volume)"
    }
   },
   {
    "name": "interfaces",
    "query": {
     "query": "label_values(windows_net_bytes_total,nic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proofs Found",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_proofs_total" }
   ]
  },
  {
   "title": "Plots",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_plots_total", "legendFormat": "Plots" }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_latency_seconds_total{volume=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Thoughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_logical_disk_reads_total{volume=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "irate(windows_logical_disk_writes_total{volume=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Search Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(chia_harvester_search_time_bucket[$__rate_interval])) by (le,plots_eligible))",
     "legendFormat": "{{plots_eligible}} Plots Passed Filter"
    }
   ]
  },
  {
   "title": "Search Time Histogram (at least one plot passed filter)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_harvester_search_time_bucket{plots_eligible!=\"0\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(windows_cpu_time_total{mode!=\"idle\"}[$__rate_interval])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_logical_disk_size_bytes{volume=~\"$disks\"} - windows_logical_disk_free_bytes{volume=~\"$disks\"}) / windows_logical_disk_size_bytes{volume=~\"$disks\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_blockchain_sync_status", "legendFormat": "status" },
    {
     "expr": "chia_peers_count{type=\"1\"}",
     "legendFormat": "peers"
    },
    { "expr": "chia_blockchain_space_bytes", "legendFormat": "netspace" }
   ]
  },
  {
   "title": "Network Usage (last 24hr)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$node\",device=~\"$interfaces\"}[24h]))",
     "legendFormat": " rx"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$node\",device=~\"$interfaces\"}[24h]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes - windows_os_physical_memory_free_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}