{
 "title": "Chia",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_filesystem_size, instance)"
    }
   },
   {
    "name": "mounts",
    "query": {
     "query": "label_values(node_filesystem_size, mountpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proofs Found",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_proofs_total" }
   ]
  },
  {
   "title": "Plots",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_plots_total", "legendFormat": "Plots" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size{mountpoint=~\"$mounts\"} - node_filesystem_avail{mountpoint=~\"$mounts\"})/ node_filesystem_size{mountpoint=~\"$mounts\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Search Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(chia_harvester_search_time_bucket[$__rate_interval])) by (le,plots_eligible))",
     "legendFormat": "{{plots_eligible}} Plots Past Filter"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=\"$node\"} - node_memory_MemFree{instance=\"$node\"} - node_memory_Buffers{instance=\"$node\"} - node_memory_Cached{instance=\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers{instance=\"$node\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached{instance=\"$node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree{instance=\"$node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Search Time Histogram (at least one plot passed filter)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_harvester_search_time_bucket{plots_eligible!=\"0\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}